[2018-01-03 20:17:34,992] [ERROR] [Error] - 程序启动开始
[2018-01-03 20:18:39,060] [ERROR] [Error] - 程序启动开始
[2018-01-03 20:18:42,819] [ERROR] [Error] - 程序启动完成,用时：3875毫秒
[2018-01-03 20:22:57,204] [ERROR] [Error] - 程序启动开始
[2018-01-03 20:22:58,571] [ERROR] [Error] - 程序启动完成,用时：1547毫秒
[2018-01-03 20:24:09,119] [ERROR] [Error] - 程序启动开始
[2018-01-03 20:24:10,430] [ERROR] [Error] - 程序启动完成,用时：1433毫秒
[2018-01-03 20:29:46,240] [ERROR] [Error] - 程序启动开始
[2018-01-03 20:29:47,523] [ERROR] [Error] - 程序启动完成,用时：1417毫秒
[2018-01-03 20:32:46,530] [ERROR] [Error] - 程序启动开始
[2018-01-03 20:32:47,821] [ERROR] [Error] - 程序启动完成,用时：1428毫秒
[2018-01-03 20:35:19,205] [ERROR] [Error] - 程序启动开始
[2018-01-03 20:35:20,532] [ERROR] [Error] - 程序启动完成,用时：1628毫秒
[2018-01-03 20:37:52,202] [ERROR] [Error] - 程序启动开始
[2018-01-03 20:37:53,459] [ERROR] [Error] - 程序启动完成,用时：1375毫秒
[2018-01-03 20:52:54,926] [ERROR] [Error] - 程序启动开始
[2018-01-03 20:52:58,261] [ERROR] [Error] - 程序启动完成,用时：3445毫秒
[2018-01-03 20:53:28,870] [ERROR] [Error] - 程序启动开始
[2018-01-03 20:53:31,750] [ERROR] [Error] - 程序启动完成,用时：2993毫秒
[2018-01-03 21:04:14,498] [ERROR] [Error] - 程序启动开始
[2018-01-03 21:04:17,723] [ERROR] [Error] - 程序启动完成,用时：3348毫秒
[2018-01-03 21:04:45,302] [ERROR] [Error] - 程序启动开始
[2018-01-03 21:04:48,187] [ERROR] [Error] - 程序启动完成,用时：3000毫秒
[2018-01-03 21:14:33,872] [ERROR] [Error] - 程序启动开始
[2018-01-03 21:14:35,206] [ERROR] [Error] - 程序启动完成,用时：1510毫秒
[2018-01-03 21:17:01,662] [ERROR] [Error] - 程序启动开始
[2018-01-03 21:17:03,043] [ERROR] [Error] - 程序启动完成,用时：1553毫秒
[2018-01-03 21:17:48,319] [ERROR] [Error] - 程序启动开始
[2018-01-03 21:17:52,028] [ERROR] [Error] - 程序启动完成,用时：3827毫秒
[2018-01-04 22:13:19,038] [ERROR] [Error] - 程序启动开始
[2018-01-04 22:13:23,875] [ERROR] [Error] - 程序启动完成,用时：4980毫秒
[2018-01-05 21:13:08,364] [ERROR] [Error] - 程序启动开始
[2018-01-05 21:13:11,869] [ERROR] [Error] - 程序启动完成,用时：3632毫秒
[2018-01-05 21:14:06,789] [ERROR] [Error] - 程序启动开始
[2018-01-05 21:14:09,846] [ERROR] [Error] - 程序启动完成,用时：3200毫秒
[2018-01-05 22:23:54,392] [ERROR] [Error] - 程序启动开始
[2018-01-05 22:23:55,973] [ERROR] [Error] - 程序启动完成,用时：1763毫秒
[2018-01-05 22:32:54,811] [ERROR] [Error] - 程序启动开始
[2018-01-05 22:32:56,114] [ERROR] [Error] - 程序启动完成,用时：1430毫秒
[2018-01-05 22:34:23,194] [ERROR] [Error] - 程序启动开始
[2018-01-05 22:34:24,451] [ERROR] [Error] - 程序启动完成,用时：1382毫秒
[2018-01-05 22:38:50,731] [ERROR] [Error] - 程序启动开始
[2018-01-05 22:38:54,108] [ERROR] [Error] - 程序启动完成,用时：3496毫秒
[2018-01-05 22:40:22,049] [ERROR] [Error] - 程序启动开始
[2018-01-05 22:40:24,994] [ERROR] [Error] - 程序启动完成,用时：3064毫秒
[2018-01-05 22:48:15,044] [ERROR] [Error] - 程序启动开始
[2018-01-05 22:48:16,497] [ERROR] [Error] - 程序启动完成,用时：1620毫秒
[2018-01-05 22:52:53,392] [ERROR] [Error] - 程序启动开始
[2018-01-05 22:52:54,710] [ERROR] [Error] - 程序启动完成,用时：1440毫秒
[2018-01-05 22:55:00,034] [ERROR] [Error] - 程序启动开始
[2018-01-05 22:55:01,326] [ERROR] [Error] - 程序启动完成,用时：1415毫秒
[2018-01-05 23:00:08,317] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:00:09,599] [ERROR] [Error] - 程序启动完成,用时：1459毫秒
[2018-01-05 23:02:57,267] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:02:58,633] [ERROR] [Error] - 程序启动完成,用时：1510毫秒
[2018-01-05 23:06:04,335] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:06:05,615] [ERROR] [Error] - 程序启动完成,用时：1403毫秒
[2018-01-05 23:10:07,381] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:10:10,662] [ERROR] [Error] - 程序启动完成,用时：3397毫秒
[2018-01-05 23:10:40,834] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:10:43,889] [ERROR] [Error] - 程序启动完成,用时：3170毫秒
[2018-01-05 23:12:52,586] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:12:54,051] [ERROR] [Error] - 程序启动完成,用时：1642毫秒
[2018-01-05 23:15:08,162] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:15:12,068] [ERROR] [Error] - 程序启动完成,用时：4040毫秒
[2018-01-05 23:16:52,297] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:16:53,620] [ERROR] [Error] - 程序启动完成,用时：1486毫秒
[2018-01-05 23:21:03,514] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:21:04,852] [ERROR] [Error] - 程序启动完成,用时：1473毫秒
[2018-01-05 23:22:43,663] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:22:44,968] [ERROR] [Error] - 程序启动完成,用时：1428毫秒
[2018-01-05 23:30:28,266] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:30:29,592] [ERROR] [Error] - 程序启动完成,用时：1458毫秒
[2018-01-05 23:31:03,624] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:31:07,138] [ERROR] [Error] - 程序启动完成,用时：3658毫秒
[2018-01-05 23:36:14,855] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:36:18,873] [ERROR] [Error] - 程序启动完成,用时：4150毫秒
[2018-01-05 23:37:46,878] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:37:50,188] [ERROR] [Error] - 程序启动完成,用时：3457毫秒
[2018-01-05 23:42:32,675] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:42:34,137] [ERROR] [Error] - 程序启动完成,用时：1643毫秒
[2018-01-05 23:43:10,328] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:43:14,007] [ERROR] [Error] - 程序启动完成,用时：3798毫秒
[2018-01-05 23:53:42,592] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:53:44,038] [ERROR] [Error] - 程序启动完成,用时：1620毫秒
[2018-01-05 23:54:19,493] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:54:23,383] [ERROR] [Error] - 程序启动完成,用时：4008毫秒
[2018-01-05 23:55:09,226] [ERROR] [Error] - 程序启动开始
[2018-01-05 23:55:10,631] [ERROR] [Error] - 程序启动完成,用时：1582毫秒
[2018-01-06 00:00:03,995] [ERROR] [Error] - 程序启动开始
[2018-01-06 00:00:05,441] [ERROR] [Error] - 程序启动完成,用时：1615毫秒
[2018-01-06 00:01:20,072] [ERROR] [Error] - 程序启动开始
[2018-01-06 00:01:23,596] [ERROR] [Error] - 程序启动完成,用时：3641毫秒
[2018-01-06 00:03:42,869] [ERROR] [Error] - 程序启动开始
[2018-01-06 00:03:44,171] [ERROR] [Error] - 程序启动完成,用时：1460毫秒
[2018-01-06 22:54:58,717] [ERROR] [Error] - 程序启动开始
[2018-01-06 22:55:02,331] [ERROR] [Error] - 程序启动完成,用时：3734毫秒
[2018-01-06 22:56:25,596] [ERROR] [Error] - 程序启动开始
[2018-01-06 22:56:28,692] [ERROR] [Error] - 程序启动完成,用时：3228毫秒
[2018-01-06 23:29:29,657] [ERROR] [Error] - 程序启动开始
[2018-01-06 23:29:33,056] [ERROR] [Error] - 程序启动完成,用时：3528毫秒
[2018-01-21 22:11:43,292] [ERROR] [Error] - 程序启动开始
[2018-01-21 22:11:47,423] [ERROR] [Error] - 注册定时服务失败:System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 SolutionWeb.TimerConfig.RegisterTimerConfig() 位置 D:\work\zcdx\trunk\code\SolutionWeb\App_Start\TimerConfig.cs:行号 26
[2018-01-21 22:11:47,434] [ERROR] [Error] - 程序启动完成,用时：4366毫秒
[2018-01-21 22:12:36,121] [ERROR] [Error] - 程序启动开始
[2018-01-21 22:12:37,437] [ERROR] [Error] - 注册定时服务失败:System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 SolutionWeb.TimerConfig.RegisterTimerConfig() 位置 D:\work\zcdx\trunk\code\SolutionWeb\App_Start\TimerConfig.cs:行号 26
[2018-01-21 22:12:37,443] [ERROR] [Error] - 程序启动完成,用时：1480毫秒
[2018-01-21 22:13:00,448] [ERROR] [Error] - 程序启动开始
[2018-01-21 22:13:03,899] [ERROR] [Error] - 注册定时服务失败:System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 SolutionWeb.TimerConfig.RegisterTimerConfig() 位置 D:\work\zcdx\trunk\code\SolutionWeb\App_Start\TimerConfig.cs:行号 26
[2018-01-21 22:13:03,904] [ERROR] [Error] - 程序启动完成,用时：3602毫秒
[2018-01-21 22:13:28,056] [ERROR] [Error] - 程序启动开始
[2018-01-21 22:13:31,261] [ERROR] [Error] - 注册定时服务失败:System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 SolutionWeb.TimerConfig.RegisterTimerConfig() 位置 D:\work\zcdx\trunk\code\SolutionWeb\App_Start\TimerConfig.cs:行号 26
[2018-01-21 22:13:31,267] [ERROR] [Error] - 程序启动完成,用时：3317毫秒
[2018-01-21 22:13:50,971] [ERROR] [Error] - 程序启动开始
[2018-01-21 22:13:52,565] [ERROR] [Error] - 注册定时服务失败:System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 SolutionWeb.TimerConfig.RegisterTimerConfig() 位置 D:\work\zcdx\trunk\code\SolutionWeb\App_Start\TimerConfig.cs:行号 26
[2018-01-21 22:13:52,571] [ERROR] [Error] - 程序启动完成,用时：1753毫秒
[2018-01-21 22:14:20,151] [ERROR] [Error] - 程序启动开始
[2018-01-21 22:14:23,361] [ERROR] [Error] - 注册定时服务失败:System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 SolutionWeb.TimerConfig.RegisterTimerConfig() 位置 D:\work\zcdx\trunk\code\SolutionWeb\App_Start\TimerConfig.cs:行号 26
[2018-01-21 22:14:23,367] [ERROR] [Error] - 程序启动完成,用时：3362毫秒
[2018-01-21 23:10:46,878] [ERROR] [Error] - 程序启动开始
[2018-01-21 23:10:50,274] [ERROR] [Error] - 注册定时服务失败:System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 SolutionWeb.TimerConfig.RegisterTimerConfig() 位置 D:\work\zcdx\trunk\code\SolutionWeb\App_Start\TimerConfig.cs:行号 26
[2018-01-21 23:10:50,285] [ERROR] [Error] - 程序启动完成,用时：3519毫秒
[2018-01-21 23:12:50,765] [ERROR] [Error] - 程序启动开始
[2018-01-21 23:12:53,986] [ERROR] [Error] - 定时服务POLICY_TIMER启动:2018-01-21 23:12:53
[2018-01-21 23:12:53,986] [ERROR] [Error] - 注册定时服务成功
[2018-01-21 23:12:53,991] [ERROR] [Error] - 程序启动完成,用时：3345毫秒
[2018-01-21 23:13:56,443] [ERROR] [Error] - 事项公示出错：System.Data.SqlClient.SqlException (0x80131904): 在数据库 'master' 中拒绝了 CREATE DATABASE 权限。
   在 System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   在 System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   在 System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   在 System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   在 System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.SqlServer.SqlProviderServices.<>c__DisplayClass1a.<CreateDatabaseFromScript>b__19(DbConnection conn)
   在 System.Data.Entity.SqlServer.SqlProviderServices.<>c__DisplayClass33.<UsingConnection>b__32()
   在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   在 System.Data.Entity.SqlServer.SqlProviderServices.UsingConnection(DbConnection sqlConnection, Action`1 act)
   在 System.Data.Entity.SqlServer.SqlProviderServices.UsingMasterConnection(DbConnection sqlConnection, Action`1 act)
   在 System.Data.Entity.SqlServer.SqlProviderServices.CreateDatabaseFromScript(Nullable`1 commandTimeout, DbConnection sqlConnection, String createDatabaseScript)
   在 System.Data.Entity.SqlServer.SqlProviderServices.DbCreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
   在 System.Data.Entity.Core.Common.DbProviderServices.CreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
   在 System.Data.Entity.Core.Objects.ObjectContext.CreateDatabase()
   在 System.Data.Entity.Migrations.Utilities.DatabaseCreator.Create(DbConnection connection)
   在 System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   在 System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   在 System.Data.Entity.Internal.DatabaseCreator.CreateDatabase(InternalContext internalContext, Func`3 createMigrator, ObjectContext objectContext)
   在 System.Data.Entity.Internal.InternalContext.CreateDatabase(ObjectContext objectContext, DatabaseExistenceState existenceState)
   在 System.Data.Entity.Database.Create(DatabaseExistenceState existenceState)
   在 System.Data.Entity.CreateDatabaseIfNotExists`1.InitializeDatabase(TContext context)
   在 System.Data.Entity.Internal.InternalContext.<>c__DisplayClassf`1.<CreateInitializationAction>b__e()
   在 System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   在 System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   在 System.Data.Entity.Internal.LazyInternalContext.<InitializeDatabase>b__4(InternalContext c)
   在 System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   在 System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   在 System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()
   在 System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   在 System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   在 System.Data.Entity.Internal.Linq.InternalSet`1.AsNoTracking()
   在 System.Data.Entity.Infrastructure.DbQuery`1.AsNoTracking()
   在 SolutionWeb.Service.BaseService.Entities[T]()
   在 SolutionWeb.Models.Model_POLICY_MAIN_INFO.Task()
ClientConnectionId:01ee0060-6b64-41ae-aa43-cb60711db6d5
Error Number:262,State:1,Class:14
[2018-01-21 23:14:39,326] [ERROR] [Error] - 事项公示出错：System.Data.DataException: 初始化数据库时发生异常。有关详细信息，请参阅 InnerException。 ---> System.Data.Entity.Core.EntityException: 基础提供程序在 Open 上失败。 ---> System.Data.SqlClient.SqlException: 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception: 找不到网络路径。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<Open>b__36(DbConnection t, DbConnectionInterceptionContext c)
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   在 System.Data.Entity.Core.EntityClient.EntityConnection.<Open>b__2()
   在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   在 System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   在 System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   在 System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   在 System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   在 System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__1[TResult](IEnumerable`1 sequence)
   在 System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   在 System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   在 System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   在 System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   在 System.Data.Entity.Internal.EdmMetadataRepository.QueryForModelHash(Func`2 createContext)
   在 System.Data.Entity.Internal.InternalContext.QueryForModelHash()
   在 System.Data.Entity.Internal.ModelCompatibilityChecker.CompatibleWithModel(InternalContext internalContext, ModelHashCalculator modelHashCalculator, Boolean throwIfNoMetadata, DatabaseExistenceState existenceState)
   在 System.Data.Entity.Internal.InternalContext.CompatibleWithModel(Boolean throwIfNoMetadata, DatabaseExistenceState existenceState)
   在 System.Data.Entity.CreateDatabaseIfNotExists`1.InitializeDatabase(TContext context)
   在 System.Data.Entity.Internal.InternalContext.<>c__DisplayClassf`1.<CreateInitializationAction>b__e()
   在 System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   在 System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   在 System.Data.Entity.Internal.LazyInternalContext.<InitializeDatabase>b__4(InternalContext c)
   在 System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   在 System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   在 System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()
   在 System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   在 System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   在 System.Data.Entity.Internal.Linq.InternalSet`1.AsNoTracking()
   在 System.Data.Entity.Infrastructure.DbQuery`1.AsNoTracking()
   在 SolutionWeb.Service.BaseService.Entities[T]()
   在 SolutionWeb.Models.Model_POLICY_MAIN_INFO.Task()
[2018-01-21 23:18:39,585] [ERROR] [Error] - 程序启动开始
[2018-01-21 23:18:40,903] [ERROR] [Error] - 定时服务POLICY_TIMER启动:2018-01-21 23:18:40
[2018-01-21 23:18:40,903] [ERROR] [Error] - 注册定时服务成功
[2018-01-21 23:18:40,909] [ERROR] [Error] - 程序启动完成,用时：1476毫秒
[2018-01-21 23:22:37,124] [ERROR] [Error] - 程序启动开始
[2018-01-21 23:22:38,328] [ERROR] [Error] - 定时服务POLICY_TIMER启动:2018-01-21 23:22:38
[2018-01-21 23:22:38,328] [ERROR] [Error] - 注册定时服务成功
[2018-01-21 23:22:38,334] [ERROR] [Error] - 程序启动完成,用时：1329毫秒
[2018-01-21 23:23:46,923] [ERROR] [Error] - 程序启动开始
[2018-01-21 23:23:48,144] [ERROR] [Error] - 定时服务POLICY_TIMER启动:2018-01-21 23:23:48
[2018-01-21 23:23:48,144] [ERROR] [Error] - 注册定时服务成功
[2018-01-21 23:23:48,150] [ERROR] [Error] - 程序启动完成,用时：1345毫秒
[2018-01-21 23:30:02,286] [ERROR] [Error] - 程序启动开始
[2018-01-21 23:30:05,507] [ERROR] [Error] - 定时服务POLICY_TIMER启动:2018-01-21 23:30:05
[2018-01-21 23:30:05,507] [ERROR] [Error] - 注册定时服务成功
[2018-01-21 23:30:05,518] [ERROR] [Error] - 程序启动完成,用时：3360毫秒
[2018-01-21 23:31:06,861] [ERROR] [Error] - 程序启动开始
[2018-01-21 23:31:10,107] [ERROR] [Error] - 定时服务POLICY_TIMER启动:2018-01-21 23:31:10
[2018-01-21 23:31:10,107] [ERROR] [Error] - 注册定时服务成功
[2018-01-21 23:31:10,112] [ERROR] [Error] - 程序启动完成,用时：3378毫秒
[2018-01-21 23:33:37,448] [ERROR] [Error] - 程序启动开始
[2018-01-21 23:33:38,720] [ERROR] [Error] - 定时服务POLICY_TIMER启动:2018-01-21 23:33:38
[2018-01-21 23:33:38,720] [ERROR] [Error] - 注册定时服务成功
[2018-01-21 23:33:38,726] [ERROR] [Error] - 程序启动完成,用时：1437毫秒
